language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7
  - openjdk6

script: mvn test
after_success:
  - mvn clean test jacoco:report coveralls:report

