language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7
  - openjdk6

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - mvn coveralls:report

